### ISSUE TITLE
Message error deletes every message in the chat

### ISSUE THREAD

**Issue by Eytukan** [BlazeProgramming/Tucker2#4]
```javascript
if (homoglyph.search(message.content, bad.kick) || homoglyph.search(message.content, bad.ban)) {
      message.delete()
}
```
This deletes all the messages that come into the chat. I did something similar in my bot and got a similar result. Leave it to Mee6 to take care of bad words for right now

**Comment by BlazeProgramming** [comment]
Fixed this issue in a recent commit. Turns out I didn't realize how the homoglyph library works... BECAUSE THERE IS 0 DOCUMENTATION..... xD

**Comment by raumaankidwai** [comment]
BUMP

This is what I just posted in chat. It deserves a read IMO.

```
;_;
look this up @everyone
"npm left-pad"
0_0
XD
this is the same problem with tucker
all the messages in the chat were being deleted a while ago
by tucker
because blaze decided to require a basic module that could be replaced by a one-liner in 15 minutes
and that module failed
https://github.com/CosignCosine/Tucker2/issues/4
```

@CosignCosine can we get on this?

**Comment by CosignCosine** [comment]
I fixed this issue a long time ago... and I'm pretty sure I pushed to GitHub....

I required the basic module because I didn't want to spend the time writing down every single homoglyph on a one-liner. Plus, that would be messy.

`left-pad` does not do what `homoglyph-search` does.

**Comment by raumaankidwai** [comment]
True. But just do this.
```js
for (<increment through bad words>) {
    var badWord = <bad words array>[<counter>];
    if (new RegExp(badWord.split("").join("[\W ]?"), "g").test(message)) {
        return sendWarning();
    }
}
```
I don't know how to adapt this to Tucker, but that shouldn't be too hard.

**Comment by Eytukan** [comment]
there is an easier way...
do something like 
```javascript
message.split();
for (<loop through message>) {
       if (<bad words array>.indexOf(<message array>[<counter>]) !== -1) {
             return sendWarning();
       }
}
```
this was just thrown togther and it has a little bit of extra stuff

**Comment by CosignCosine** [comment]
Still not sure if anyone understands what the homoglyph library does.

Let's say I say "BaIls" in chat. If "Balls" were blocked, then "BaIls" would be fine, because it's actually "Bails", which isn't blocked. The library will not only block "Balls" but also "BaIls".

Plus, I already created a bad word searcher for my KA Wiki bot, remember? xD

**Comment by raumaankidwai** [comment]
Again, not that hard. Replace the ells with eyes in the bad words and try again. Make a generalized array of substitutions to watch out for, implement that in about 30 mins, you got a functioning function that don't need no undocumented libraries.

**Comment by CosignCosine** [comment]
It's easier and cleaner overall to simply include a library and do a short one-liner.

**Comment by raumaankidwai** [comment]
If it doesn't have docs like you said, it's probably not reliable in terms of staying on as an NPM package.

**Comment by CosignCosine** [comment]
I have the library saved to my hard drive, that should not be a problem. If it disappears from npm, I will include it as a Gith
